version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    container_name: progstack_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - './internal/model/:/docker-entrypoint-initdb.d/'
    restart: unless-stopped
