services:
  progstack:
    container_name: progstack_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7999:7999'
    volumes:
      - './repositories:/app/repositories'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:12-alpine
    container_name: postgres_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    volumes:
      - './internal/model/:/docker-entrypoint-initdb.d/'
    restart: unless-stopped

volumes:
  repositories:
